<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  
  <!-- For database: add embedded resource -->
  <ItemGroup>
    <EmbeddedResource Include="Database\foods-data-set.json" />
  </ItemGroup>

</Project>
